services:
  gamiscreen-server:
    image: lklimek/gamiscreen-server:latest
    container_name: gamiscreen-server
    restart: unless-stopped
    ports:
      - "5151:5151"
    environment:
      - RUST_LOG=info,gamiscreen_server=debug
      - CONFIG_PATH=/etc/gamiscreen/config.yaml
      - DB_PATH=/var/lib/gamiscreen/app.db
    volumes:
      # Persist the SQLite database in a named volume
      - gamiscreen-data:/var/lib/gamiscreen

volumes:
  gamiscreen-data:
