services:
  gamiscreen-server:
    build:
      context: .
      dockerfile: gamiscreen-server/Dockerfile
    image: gamiscreen/server:latest
    container_name: gamiscreen-server
    restart: unless-stopped
    ports:
      - "5151:5151"
    environment:
      - RUST_LOG=info,gamiscreen_server=debug
      - CONFIG_PATH=/etc/gamiscreen/config.yaml
      - DB_PATH=/var/lib/gamiscreen/app.db
    volumes:
      # Mount the configuration directory as read-only
      - gamiscreen-config:/etc/gamiscreen:ro
      # Persist the SQLite database in a named volume
      - gamiscreen-data:/var/lib/gamiscreen

volumes:
  gamiscreen-config:
  gamiscreen-data:
