#[cfg(feature = "ts")]
use std::{fs, io::Write, path::Path};

#[cfg(feature = "ts")]
use ts_rs::{Config, TS};

#[cfg(feature = "ts")]
use super::{
    AuthReq, AuthResp, ChildDto, ClientRegisterReq, ClientRegisterResp, ConfigResp, HeartbeatReq,
    HeartbeatResp, NotificationItemDto, NotificationsCountDto, PushSubscribeReq, PushSubscribeResp,
    PushUnsubscribeReq, RemainingDto, RewardHistoryItemDto, RewardReq, RewardResp, SubmitTaskReq,
    TaskDto, TaskWithStatusDto, UpdateArtifactDto, UpdateItemDto, UpdateManifestDto,
    UsageBucketDto, UsageSeriesDto, VersionInfoDto,
};
#[cfg(feature = "ts")]
use crate::{auth::Role, jwt::JwtClaims};

#[cfg(feature = "ts")]
pub fn export_types(path: impl AsRef<Path>) -> std::io::Result<()> {
    let path = path.as_ref();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut file = fs::File::create(path)?;

    writeln!(
        file,
        "// This file is @generated by gamiscreen-server/build.rs\n// Do not edit manually.\n"
    )?;

    let config = Config::default();
    let mut write_decl = |decl: String| -> std::io::Result<()> {
        let trimmed = decl.trim();
        if trimmed.is_empty() {
            return Ok(());
        }
        let exported = if let Some(rest) = trimmed.strip_prefix("interface ") {
            format!("export interface {}", rest)
        } else if let Some(rest) = trimmed.strip_prefix("type ") {
            format!("export type {}", rest)
        } else {
            trimmed.to_string()
        };
        writeln!(file, "{}\n", exported)?;
        Ok(())
    };

    write_decl(AuthReq::decl(&config))?;
    write_decl(AuthResp::decl(&config))?;
    write_decl(ChildDto::decl(&config))?;
    write_decl(TaskDto::decl(&config))?;
    write_decl(TaskWithStatusDto::decl(&config))?;
    write_decl(RemainingDto::decl(&config))?;
    write_decl(RewardReq::decl(&config))?;
    write_decl(RewardResp::decl(&config))?;
    write_decl(HeartbeatReq::decl(&config))?;
    write_decl(HeartbeatResp::decl(&config))?;
    write_decl(ConfigResp::decl(&config))?;
    write_decl(PushSubscribeReq::decl(&config))?;
    write_decl(PushSubscribeResp::decl(&config))?;
    write_decl(PushUnsubscribeReq::decl(&config))?;
    write_decl(ClientRegisterReq::decl(&config))?;
    write_decl(ClientRegisterResp::decl(&config))?;
    write_decl(RewardHistoryItemDto::decl(&config))?;
    write_decl(UsageBucketDto::decl(&config))?;
    write_decl(UsageSeriesDto::decl(&config))?;
    write_decl(SubmitTaskReq::decl(&config))?;
    write_decl(NotificationsCountDto::decl(&config))?;
    write_decl(NotificationItemDto::decl(&config))?;
    write_decl(UpdateManifestDto::decl(&config))?;
    write_decl(UpdateItemDto::decl(&config))?;
    write_decl(UpdateArtifactDto::decl(&config))?;
    write_decl(VersionInfoDto::decl(&config))?;
    write_decl(Role::decl(&config))?;
    write_decl(JwtClaims::decl(&config))?;

    Ok(())
}
