# Example config for gamiscreen-client
# Place as: ~/.config/gamiscreen/client.yaml

server_url: "http://127.0.0.1:5151"
# Child/device identifiers now come from the JWT returned during `gamiscreen-client login`.
# Heartbeats run every 60 seconds with a built-in 45 second pre-lock countdown.
# Locks via org.freedesktop.login1 Manager (DBus). Ensure polkit rule installed.
