# Example config for gamiscreen-client
# Place as: ~/.config/gamiscreen/client.yaml

server_url: "http://127.0.0.1:5151"
child_id: "alice"
device_id: "alice-pc"
# Optional (defaults shown)
# interval_secs: 60
# warn_before_lock_secs: 10
# Locks via org.freedesktop.login1 Manager (DBus). Ensure polkit rule installed.
