name: Release Binaries

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build-client-linux-x86_64:
    name: Build gamiscreen-client (linux x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libdbus-1-dev libsqlite3-dev

      - name: Build client
        env:
          SKIP_WEB_BUILD: "1"
        run: |
          cargo build --release -p gamiscreen-client
          cp target/release/gamiscreen-client gamiscreen-client-linux-x86_64
          sha256sum gamiscreen-client-linux-x86_64 | awk '{print $1}' > gamiscreen-client-linux-x86_64.sha256

      - name: Upload release assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            gamiscreen-client-linux-x86_64
            gamiscreen-client-linux-x86_64.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts (manual runs)
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: gamiscreen-client-linux-x86_64
          path: |
            gamiscreen-client-linux-x86_64
            gamiscreen-client-linux-x86_64.sha256
